# Generated by Django 4.1.5 on 2023-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('pno', models.CharField(max_length=50, verbose_name='')),
                ('desc', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
    ]
